### ISSUE TITLE
IPN / Callback issue

### ISSUE THREAD

**Issue by Benspring100** [MineSQL/CoinPayments#6]
When I have paid the amount in BTC it said PAID but it won't redirect or anything back to my website. It just gets stuck. I set my IPN_URL to the callback script on my server. 

Am I being stupid? What am I doing wrong?

**Comment by MineSQL** [comment]
You'll need to post your code...

Read coinpayments.net documentation as well, if you aren't familiar with their system then there is no reason to be using this library.

**Comment by Benspring100** [comment]
`$CP->setFormElement('currency', 'BTC');
$CP->setFormElement('amountf',0.00019);
$CP->setFormElement('item_name', 'Test Item');




//OPTIONAL
$CP->setFormElement('custom', 'customValue235');
$CP->setFormElement('ipn_url', 'http://minesql.me/ipn/cp');`

Then I changed the http://minesql.me/ipn/cp to my callback (localhost/callback.php).

**Comment by RonMelkhior** [comment]
Coinpayments uses the `ipn_url` you provided to contact you, if you give them `localhost`, it will contact itself, not you.

Give your IP/URL in `ipn_url`.

**Comment by Benspring100** [comment]
CODE:
``$CP->setFormElement('currency', 'BTC');
$CP->setFormElement('amountf',0.0002);
$CP->setFormElement('item_name', 'Test Item');

$CP->setFormElement('custom', 'customValue235');
$CP->setFormElement('ipn_url', 'http://middleman.pw/CoinPayments-master/callback.php');``

https://i.gyazo.com/91094867c04a69adf3d358dc7b147e90.png
I still just get that. Just to clarify, the user won't be redirected back to the callback.php, the callback gets run in the background (persay) and executes a command right??

Changed all my settings, nothing seems to happen.

**Comment by RonMelkhior** [comment]
> I still just get that. Just to clarify, the user won't be redirected back to the callback.php, the callback gets run in the background (persay) and executes a command right??

correct. read the coinpayments documentation if you need to know more. (which you probably do if you didn't know this)

**Comment by MineSQL** [comment]
All you need to do is read the documentation, this isn't an issue with the wrapper, so I'm closing this issue.
