### ISSUE TITLE
Passing "Custom" to my IPN but its not being set?

### ISSUE THREAD

**Issue by benspring** [MineSQL/CoinPayments#7]
I am passing custom (the passthru variable) to the IPN but I cannot call it in your callback.php file.

For example:
$CP->setFormElement('custom', 'Example1'); - In creating transaction.

Attempting to call it: $_POST['custom'] = However, it returns nothing. 

One last thing, is there a better way to test this rather than my consistently creating a transaction and in my callback file inserting it into a database. 

Nevertheless, any ideas on why I cannot call the custom variable?

**Comment by benspring** [comment]
And, I really hate to constantly keep asking you. I made a post on another forum and read the coinpayment documentation (which said the custom is being passed through to the IPN), but cannot figure out why it doesn't work.

Many Thanks,
Ben

**Comment by MineSQL** [comment]
https://www.coinpayments.net/merchant-tools-ipn

I'm not really sure what issues your having, but I don't give out support for a problem that isn't directly related to my library. I suggest that you read there documentation and try their example code (not using my library), if that works fine then I can look into your issue, but I'm betting that it is an issue with your setup. People have used this before and have not ran into any issues using the documentation supplied by coinpayments and me. I've personally used it many times and never ran into any issues.

I continually urge you to read the coin payments documentation, so you probably should. I will hand out specific implementations to every user that uses my library.
